server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: lizhengasd123


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #????,????true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

reggie:
  path: C:\Users\李咨辰\Desktop\reggie\2 上传的图片\


